// Generated by ts-to-zod
import { z } from "zod";

export const pathPartsSchema = z.object({
  subdirs: z.array(z.string()),
  depth: z.number(),
  filename: z.string(),
  stem: z.string(),
  ext: z.string(),
  parentRel: z.string(),
  relativePath: z.string(),
});

export const fileEntrySchema = z.object({
  relativePath: z.string(),
  absolutePath: z.string(),
  parts: pathPartsSchema,
  fileType: z.string(),
  sizeBytes: z.number(),
  mtimeNs: z.number(),
  depth: z.number(),
  sha256: z.string().optional().nullable(),
});

export const fileTypeIndexSchema = z.object({
  root: z.string(),
  fileType: z.string(),
  count: z.number(),
  totalBytes: z.number(),
  entries: z.array(fileEntrySchema),
  scannedDirs: z.number(),
  elapsedMs: z.number(),
  indexedAt: z.string(),
});

export const indexResultSchema = z.object({
  root: z.string(),
  indexes: z.array(fileTypeIndexSchema),
  elapsedMs: z.number(),
});
